window.SWEET_EARTH_LOCATIONS = {
  locations: [
    {
      id: "kitchen-pickup",
      name: "Sweet Earth Delights — Home Kitchen Pickup",
      category: "pickup",
      address: "Bellevue, NE",
      city: "Bellevue",
      state: "NE",
      zip: "68005",
      lat: 41.1544,
      lng: -95.9378,
      hours: "By appointment · order ahead",
      schedule: "Year-round",
      featured: true,
      description:
        "Pre-order sourdough, bagels, and pastries for pickup from our licensed home kitchen in Bellevue.",
    },
    {
      id: "papillion-farmers-market",
      name: "Papillion Farmers Market",
      category: "market",
      address: "Papillion, NE",
      city: "Papillion",
      state: "NE",
      zip: "68046",
      lat: 41.1549,
      lng: -96.0422,
      hours: "Wednesdays during market season",
      schedule: "Wednesday",
      featured: true,
      description: "Find Sweet Earth Delights sourdough and seasonal bakes at the Papillion Farmers Market.",
    },
    {
      id: "downtown-omaha-farmers-market",
      name: "Downtown Omaha Farmers Market",
      category: "market",
      address: "Omaha, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2565,
      lng: -95.9345,
      hours: "Saturdays during market season",
      schedule: "Saturday",
      featured: true,
      description: "Downtown Omaha market stop for fresh sourdough loaves, bagels, and pastries.",
    },
    {
      id: "bellevue-farmers-market",
      name: "Bellevue Farmers Market",
      category: "market",
      address: "Bellevue, NE",
      city: "Bellevue",
      state: "NE",
      zip: "68005",
      lat: 41.1486,
      lng: -95.9142,
      hours: "Saturdays during market season",
      schedule: "Saturday",
      featured: true,
      description: "Meet us close to home for bread baked fresh for market day in Bellevue.",
    },
    {
      id: "gretna-farmers-market",
      name: "Gretna Farmers Market",
      category: "market",
      address: "Gretna, NE",
      city: "Gretna",
      state: "NE",
      zip: "68028",
      lat: 41.1408,
      lng: -96.2398,
      hours: "Saturdays during market season",
      schedule: "Saturday",
      featured: false,
      description: "Gretna market mornings with sourdough and rotating seasonal favorites.",
    },
    {
      id: "aksarben-village-farmers-market",
      name: "Aksarben Village Farmers Market",
      category: "market",
      address: "Omaha, NE",
      city: "Omaha",
      state: "NE",
      zip: "68106",
      lat: 41.2392,
      lng: -96.0048,
      hours: "Sundays when invited",
      schedule: "Sunday · seasonal",
      featured: false,
      description: "We join the Aksarben Village Farmers Market on select Sundays when invited.",
    },
    {
      id: "huffman-produce",
      name: "Huffman Produce",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2482,
      lng: -95.9481,
      hours: "Store hours vary",
      schedule: "Monday · Thursday delivery",
      featured: false,
      description: "Weekly delivery of Sweet Earth Delights sourdough. Availability updated each bake.",
    },
    {
      id: "cream-of-the-crop",
      name: "Cream of the Crop Farm Stand",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2614,
      lng: -95.9624,
      hours: "Store hours vary",
      schedule: "Tuesday · Friday delivery",
      featured: false,
      description: "Farm stand carrying our sourdough on Tuesday and Friday delivery days.",
    },
    {
      id: "takeroot-farm-stop",
      name: "TakeRoot Farm Stop",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2538,
      lng: -95.9712,
      hours: "Store hours vary",
      schedule: "Tuesday · Thursday delivery",
      featured: false,
      description: "Local farm stop stocked with Sweet Earth Delights bread twice each week.",
    },
    {
      id: "wine-beer-spirits",
      name: "Wine, Beer & Spirits",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2571,
      lng: -95.9288,
      hours: "Store hours vary",
      schedule: "Tuesday · Thursday delivery",
      featured: false,
      description: "Grab a loaf while you shop. Fresh sourdough delivered twice weekly.",
    },
    {
      id: "marigolds-mercantile",
      name: "Marigold's Mercantile",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2446,
      lng: -95.9563,
      hours: "Store hours vary",
      schedule: "Tuesday · Thursday delivery",
      featured: false,
      description: "Neighborhood mercantile with standing weekly deliveries from our kitchen.",
    },
    {
      id: "grand-patisserie",
      name: "Grand Patisserie",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2522,
      lng: -95.9415,
      hours: "Store hours vary",
      schedule: "Thursday delivery",
      featured: false,
      description: "Thursday delivery of select Sweet Earth Delights sourdough loaves.",
    },
    {
      id: "j-gorats-deli",
      name: "J. Gorat's Deli & Marketplace",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2495,
      lng: -95.9651,
      hours: "Store hours vary",
      schedule: "Thursday delivery",
      featured: false,
      description: "Deli and marketplace shelf stocked fresh each Thursday.",
    },
    {
      id: "ellsworth-crossing",
      name: "Ellsworth Crossing",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2468,
      lng: -95.9527,
      hours: "Store hours vary",
      schedule: "Thursday delivery",
      featured: false,
      description: "Thursday sourdough delivery for shoppers in the Omaha metro.",
    },
    {
      id: "dip-cravers",
      name: "Dip Cravers",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2559,
      lng: -95.9734,
      hours: "Store hours vary",
      schedule: "Thursday delivery",
      featured: false,
      description: "Weekly Thursday drop of fresh bread from Sweet Earth Delights.",
    },
    {
      id: "viaduct-gardens",
      name: "Viaduct Gardens",
      category: "retail",
      address: "Omaha metro area, NE",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2511,
      lng: -95.9359,
      hours: "Store hours vary",
      schedule: "Thursday delivery",
      featured: false,
      description: "Thursday retail partner carrying our naturally fermented sourdough.",
    },
  ],
  retailPartners: [
    { name: "Huffman Produce", locationId: "huffman-produce" },
    { name: "Cream of the Crop Farm Stand", locationId: "cream-of-the-crop" },
    { name: "TakeRoot Farm Stop", locationId: "takeroot-farm-stop" },
    { name: "Wine, Beer & Spirits", locationId: "wine-beer-spirits" },
    { name: "Marigold's Mercantile", locationId: "marigolds-mercantile" },
    { name: "Grand Patisserie", locationId: "grand-patisserie" },
    { name: "J. Gorat's Deli & Marketplace", locationId: "j-gorats-deli" },
    { name: "Ellsworth Crossing", locationId: "ellsworth-crossing" },
    { name: "Dip Cravers", locationId: "dip-cravers" },
    { name: "Viaduct Gardens", locationId: "viaduct-gardens" },
  ],
};
