window.SWEET_EARTH_LOCATIONS = {
  locations: [
    {
      id: "kitchen-pickup",
      name: "Sweet Earth Delights — Home Kitchen Pickup",
      category: "pickup",
      address: "Bellevue, NE 68005",
      city: "Bellevue",
      state: "NE",
      zip: "68005",
      lat: 41.1544,
      lng: -95.9378,
      hours: "By appointment · order ahead",
      schedule: "Year-round",
      featured: true,
      description: "Pre-order sourdough, pastries, and seasonal bakes for pickup from our licensed home kitchen.",
    },
    {
      id: "aksarben-market",
      name: "Aksarben Village Farmers Market",
      category: "market",
      address: "2110 S 67th St, Omaha, NE 68106",
      city: "Omaha",
      state: "NE",
      zip: "68106",
      lat: 41.2392,
      lng: -96.0048,
      hours: "Saturdays · 8am – 12pm",
      schedule: "Apr – Oct 2026",
      featured: true,
      description: "Rotating selection of sourdough loaves, bagels, pastries, cookies, and seasonal favorites.",
    },
    {
      id: "old-market",
      name: "Downtown Artisan Market",
      category: "market",
      address: "1100 Jackson St, Omaha, NE 68102",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2565,
      lng: -95.9345,
      hours: "Sundays · 9am – 1pm",
      schedule: "May – Sep 2026",
      featured: true,
      description: "Small-batch breads and treats baked fresh for market day in the Old Market district.",
    },
    {
      id: "midweek-green",
      name: "Midweek Market on the Green",
      category: "market",
      address: "1801 Harvell Dr, Bellevue, NE 68005",
      city: "Bellevue",
      state: "NE",
      zip: "68005",
      lat: 41.1486,
      lng: -95.9142,
      hours: "Wednesdays · 4pm – 7pm",
      schedule: "Jun – Aug 2026",
      featured: false,
      description: "Weeknight market stop for fresh loaves and grab-and-go pastries.",
    },
    {
      id: "spring-popup",
      name: "Spring Kitchen Pop-Up",
      category: "popup",
      address: "2402 Cornhusker Rd, Bellevue, NE 68005",
      city: "Bellevue",
      state: "NE",
      zip: "68005",
      lat: 41.1621,
      lng: -95.9214,
      hours: "March 15, 2026 · 10am – 2pm",
      schedule: "One-day event",
      featured: false,
      description: "Pre-orders recommended · sourdough, pastries, and limited-run spring bakes.",
    },
    {
      id: "july-fourth",
      name: "Independence Day Bake Stand",
      category: "popup",
      address: "3200 Fort Crook Rd S, Bellevue, NE 68123",
      city: "Bellevue",
      state: "NE",
      zip: "68123",
      lat: 41.1358,
      lng: -95.9187,
      hours: "July 4, 2026 · 8am – sell out",
      schedule: "Holiday pop-up",
      featured: false,
      description: "Holiday cookies, pies, and celebration treats while supplies last.",
    },
    {
      id: "holiday-popups",
      name: "Holiday Market Pop-Ups",
      category: "popup",
      address: "Omaha–Council Bluffs metro area",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2565,
      lng: -95.9345,
      hours: "Select weekends · Nov – Dec 2026",
      schedule: "Seasonal",
      featured: false,
      description: "Gift boxes, seasonal bakes, and custom holiday orders at rotating community markets.",
    },
    {
      id: "retail-papillion",
      name: "Papillion Market Co.",
      category: "retail",
      address: "808 N Washington St, Papillion, NE 68046",
      city: "Papillion",
      state: "NE",
      zip: "68046",
      lat: 41.1549,
      lng: -96.0422,
      hours: "Store hours vary",
      schedule: "Weekly delivery",
      featured: false,
      description: "Fresh Sweet Earth sourdough on shelves — availability updated with each bake.",
      partnerLogo: "images/partners/papillion-market.svg",
    },
    {
      id: "retail-omaha",
      name: "Dundee Provisions",
      category: "retail",
      address: "5014 Underwood Ave, Omaha, NE 68132",
      city: "Omaha",
      state: "NE",
      zip: "68132",
      lat: 41.2643,
      lng: -95.9658,
      hours: "Store hours vary",
      schedule: "Weekly delivery",
      featured: false,
      description: "Grab a loaf from the shelf at this neighborhood shop in the Dundee area.",
      partnerLogo: "images/partners/dundee-provisions.svg",
    },
    {
      id: "retail-council-bluffs",
      name: "Riverfront Pantry",
      category: "retail",
      address: "1751 Madison Ave, Council Bluffs, IA 51503",
      city: "Council Bluffs",
      state: "IA",
      zip: "51503",
      lat: 41.2619,
      lng: -95.8608,
      hours: "Store hours vary",
      schedule: "Weekly delivery",
      featured: false,
      description: "Iowa-side retail partner carrying select Sweet Earth Delights breads.",
      partnerLogo: "images/partners/riverfront-pantry.svg",
    },
    {
      id: "retail-old-market",
      name: "Old Market Goods",
      category: "retail",
      address: "1314 Jones St, Omaha, NE 68102",
      city: "Omaha",
      state: "NE",
      zip: "68102",
      lat: 41.2558,
      lng: -95.9321,
      hours: "Store hours vary",
      schedule: "Twice weekly delivery",
      featured: false,
      description: "Downtown Omaha shop stocking select loaves and weekend pastry drops.",
      partnerLogo: "images/partners/old-market-goods.svg",
    },
    {
      id: "retail-aksarben",
      name: "Aksarben Village Mercantile",
      category: "retail",
      address: "2110 S 67th St, Omaha, NE 68106",
      city: "Omaha",
      state: "NE",
      zip: "68106",
      lat: 41.2401,
      lng: -96.0032,
      hours: "Store hours vary",
      schedule: "Weekly delivery",
      featured: false,
      description: "Neighborhood mercantile with a standing order of country sourdough and seasonal bakes.",
      partnerLogo: "images/partners/aksarben-mercantile.svg",
    },
    {
      id: "retail-metro",
      name: "Metro Natural Foods",
      category: "retail",
      address: "15600 W Center Rd, Omaha, NE 68130",
      city: "Omaha",
      state: "NE",
      zip: "68130",
      lat: 41.2337,
      lng: -96.1568,
      hours: "Store hours vary",
      schedule: "Weekly delivery",
      featured: false,
      description: "West Omaha natural foods market carrying our signature sourdough lineup.",
      partnerLogo: "images/partners/metro-natural-foods.svg",
    },
    {
      id: "retail-bellevue",
      name: "Bellevue Community Grocer",
      category: "retail",
      address: "1908 Harvell Dr, Bellevue, NE 68005",
      city: "Bellevue",
      state: "NE",
      zip: "68005",
      lat: 41.1498,
      lng: -95.9156,
      hours: "Store hours vary",
      schedule: "Weekly delivery",
      featured: false,
      description: "Bellevue grocer with fresh deliveries straight from our home kitchen.",
      partnerLogo: "images/partners/bellevue-community-grocer.svg",
    },
  ],
  retailPartners: [
    { name: "Dundee Provisions", logo: "images/partners/dundee-provisions.svg", locationId: "retail-omaha" },
    { name: "Papillion Market Co.", logo: "images/partners/papillion-market.svg", locationId: "retail-papillion" },
    { name: "Riverfront Pantry", logo: "images/partners/riverfront-pantry.svg", locationId: "retail-council-bluffs" },
    { name: "Old Market Goods", logo: "images/partners/old-market-goods.svg", locationId: "retail-old-market" },
    { name: "Aksarben Village Mercantile", logo: "images/partners/aksarben-mercantile.svg", locationId: "retail-aksarben" },
    { name: "Metro Natural Foods", logo: "images/partners/metro-natural-foods.svg", locationId: "retail-metro" },
    { name: "Bellevue Community Grocer", logo: "images/partners/bellevue-community-grocer.svg", locationId: "retail-bellevue" },
  ],
};
