window.SWEET_EARTH_PRODUCTS = {
  "original-loaves": {
    slug: "original-loaves",
    name: "Original Loaves",
    category: "bread",
    categoryLabel: "Sourdough Bread",
    price: "$8 – $12",
    size: "Small $8 · Medium $10 · Large $12",
    image: "images/true-sourdough-bread-omaha.jpg",
    imageAlt: "Original sourdough loaves from Sweet Earth Delights",
    shortDesc: "Classic long-fermented sourdough with a golden crust and tangy, open crumb.",
    description:
      "Our signature sourdough loaves start with a mature starter and a slow, cool ferment. Shaped by hand and baked until the crust is deep golden and crackly. Available in small, medium, and large — ask about our flavor of the month.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Sea salt",
    ],
    allergens:
      "Contains wheat. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "cinnamon-raisin": {
    slug: "cinnamon-raisin",
    name: "Cinnamon Raisin",
    category: "bread",
    categoryLabel: "Sourdough Bread",
    price: "$12 – $16",
    size: "Small $12 · Medium $14 · Large $16",
    image: "images/cinnamon-raisin-soudough-loaf.jpg",
    imageAlt: "Cinnamon raisin sourdough loaf from Sweet Earth Delights",
    shortDesc: "Tangy sourdough studded with plump raisins and a touch of cinnamon.",
    description:
      "Slow-fermented sourdough bread folded with raisins and cinnamon. Wonderful toasted with butter or cream cheese. Available in small, medium, and large.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Raisins",
      "Cinnamon",
      "Brown sugar",
      "Sea salt",
    ],
    allergens:
      "Contains wheat. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "jalapeno-cheddar": {
    slug: "jalapeno-cheddar",
    name: "Jalapeño Cheddar",
    category: "bread",
    categoryLabel: "Sourdough Bread",
    price: "$12 – $16",
    size: "Small $12 · Medium $14 · Large $16",
    image: "images/sourdough-bread-in-bellevue-ne-fresh.jpg",
    imageAlt: "Jalapeño cheddar sourdough loaf from Sweet Earth Delights",
    shortDesc: "Savory sourdough with sharp cheddar and jalapeño heat.",
    description:
      "A hearty sourdough loaf loaded with cheddar cheese and jalapeño peppers. Great for grilled cheese, alongside chili, or sliced on its own. Available in small, medium, and large.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Cheddar cheese",
      "Jalapeño peppers",
      "Sea salt",
    ],
    allergens:
      "Contains wheat and milk. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "double-chocolate-brownie": {
    slug: "double-chocolate-brownie",
    name: "Double Chocolate Brownie",
    category: "bread",
    categoryLabel: "Sourdough Bread",
    price: "$14 – $18",
    size: "Small $14 · Medium $16 · Large $18",
    image: "images/chocolate-sourdough-bread.jpg",
    imageAlt: "Double chocolate brownie sourdough loaf from Sweet Earth Delights",
    shortDesc: "Rich chocolate sourdough with a brownie-like crumb.",
    description:
      "A decadent sourdough loaf loaded with cocoa and chocolate for a deep, fudgy slice. One of our most requested flavors. Available in small, medium, and large.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Cocoa powder",
      "Chocolate",
      "Sugar",
      "Sea salt",
    ],
    allergens:
      "Contains wheat and milk. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "sourdough-focaccia": {
    slug: "sourdough-focaccia",
    name: "Focaccia",
    category: "bread",
    categoryLabel: "Sourdough Bread",
    price: "$14.00",
    size: "Whole pan",
    image: "images/foccacia-bread-omaha.jpg",
    imageAlt: "Sourdough focaccia from Sweet Earth Delights in Omaha",
    shortDesc: "Olive oil–dimpled sourdough focaccia baked fresh in Omaha.",
    description:
      "A naturally fermented sourdough focaccia finished with olive oil and sea salt. Soft inside with a golden, crisp crust — perfect for sandwiches, dipping, or serving alongside dinner. Made in small batches from our Bellevue kitchen.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Olive oil",
      "Sea salt",
    ],
    allergens:
      "Contains wheat. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "custom-bread-flavors": {
    slug: "custom-bread-flavors",
    name: "Custom Bread Flavors",
    category: "bread",
    categoryLabel: "Sourdough Bread",
    price: "Price varies",
    size: "Ask about availability",
    image: "images/TOMATO-BASIL.jpg",
    imageAlt: "Custom sourdough loaves from Sweet Earth Delights",
    shortDesc: "Have a flavor in mind? We are happy to work with you on a custom loaf.",
    description:
      "Price varies depending on ingredients. We bake many other items throughout the year — if there is something you are craving, just ask. We would be happy to make it for you.",
    ingredients: ["Varies by request"],
    allergens:
      "Allergens vary by recipe. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "browned-butter-chocolate-chip": {
    slug: "browned-butter-chocolate-chip",
    name: "Browned Butter Sourdough Chocolate Chip",
    category: "cookies",
    categoryLabel: "Cookies",
    price: "$15.00",
    size: "Per dozen",
    image: "images/sweet-earth-cookies.jpg",
    imageAlt: "Browned butter sourdough chocolate chip cookies from Sweet Earth Delights",
    shortDesc:
      "Brown butter, sourdough discard, and chocolate chips. Gluten-free +$5 · Dairy-free +$5.",
    description:
      "A dozen cookies made with nutty browned butter, sourdough discard, and chocolate chips. Gluten-free (+$5, gluten-free flour only — sourdough is not gluten-free) and dairy-free (+$5) options available.",
    ingredients: [
      "Unbleached wheat flour",
      "Sourdough discard",
      "Brown butter",
      "Brown sugar",
      "Sugar",
      "Eggs",
      "Vanilla extract",
      "Chocolate chips",
      "Sea salt",
      "Baking soda",
    ],
    allergens:
      "Contains wheat, milk, and eggs. Gluten-free and dairy-free options available. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "english-muffins": {
    slug: "english-muffins",
    name: "English Muffins (4)",
    category: "treats",
    categoryLabel: "Treats",
    price: "$8.00",
    size: "4 pack",
    image: "images/english-muffins-sweet-earth.jpg",
    imageAlt: "English muffins from Sweet Earth Delights",
    shortDesc: "Sourdough muffins with a nooks-and-crannies crumb. Split and toast.",
    description:
      "Four sourdough English muffins cooked on the griddle for that classic nooks-and-crannies texture. Split with a fork, toast until crisp, and finish with butter and jam or use for breakfast sandwiches.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Cornmeal",
      "Sea salt",
      "Baking soda",
    ],
    allergens:
      "Contains wheat. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "plain-bagels": {
    slug: "plain-bagels",
    name: "Plain Bagels (6)",
    category: "bagels",
    categoryLabel: "Bagels",
    price: "$10.00",
    size: "6 pack",
    image: "images/bagel-in-omaha-original.jpg",
    imageAlt: "Plain bagels from Sweet Earth Delights in Omaha",
    shortDesc: "Six classic bagels, hand-rolled, boiled, and baked fresh.",
    description:
      "Six plain bagels rolled by hand, boiled, and baked the morning of your pickup. Chewy inside with a glossy crust — perfect toasted with cream cheese or as the base for your favorite schmear.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Barley malt syrup",
      "Sea salt",
      "Yeast",
    ],
    allergens:
      "Contains wheat. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "everything-bagels": {
    slug: "everything-bagels",
    name: "Everything Bagels (6)",
    category: "bagels",
    categoryLabel: "Bagels",
    price: "$12.00",
    size: "6 pack",
    image: "images/everything-bagel-omaha.jpg",
    imageAlt: "Everything bagels from Sweet Earth Delights in Omaha",
    shortDesc: "Six bagels topped with everything seasoning, baked fresh.",
    description:
      "Six bagels finished with everything seasoning before baking. Hand-rolled, boiled, and baked the morning of your pickup — chewy inside with a glossy crust and garlic, onion, sesame, and poppy seeds on top.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Barley malt syrup",
      "Sea salt",
      "Yeast",
      "Everything seasoning (sesame seeds, poppy seeds, dried garlic, dried onion, salt)",
    ],
    allergens:
      "Contains wheat and sesame. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "jalapeno-cheddar-bagels": {
    slug: "jalapeno-cheddar-bagels",
    name: "Jalapeño Cheddar Bagels (6)",
    category: "bagels",
    categoryLabel: "Bagels",
    price: "$12.00",
    size: "6 pack",
    image: "images/cinnamon-cheddar-bagel.jpg",
    imageAlt: "Jalapeño cheddar bagels from Sweet Earth Delights",
    imageFit: "contain",
    shortDesc: "Six bagels topped with melted cheddar and jalapeño, baked fresh.",
    description:
      "Six hand-rolled bagels finished with sharp cheddar and jalapeño peppers before baking. Boiled and baked the morning of your pickup — chewy inside with a savory, slightly spicy bite.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Barley malt syrup",
      "Sea salt",
      "Yeast",
      "Cheddar cheese",
      "Jalapeño peppers",
    ],
    allergens:
      "Contains wheat and milk. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "french-toast-bagels": {
    slug: "french-toast-bagels",
    name: "French Toast Bagels (6)",
    category: "bagels",
    categoryLabel: "Bagels",
    price: "$12.00",
    size: "6 pack",
    image: "images/french-toast-bagel.jpg",
    imageAlt: "French toast bagels from Sweet Earth Delights",
    shortDesc: "Six bagels coated in cinnamon sugar, baked fresh.",
    description:
      "Six hand-rolled bagels finished with a sweet cinnamon-sugar coating before baking. Boiled and baked the morning of your pickup — chewy inside with a warm, french toast-inspired flavor.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Barley malt syrup",
      "Sea salt",
      "Yeast",
      "Sugar",
      "Cinnamon",
      "Butter",
    ],
    allergens:
      "Contains wheat and milk. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "sourdough-cinnamon-rolls": {
    slug: "sourdough-cinnamon-rolls",
    name: "Sourdough Cinnamon Rolls",
    category: "treats",
    categoryLabel: "Treats",
    price: "$4.50",
    size: "Single roll",
    image: "images/cinnamon-rolls-omaha-sweet-earth.jpg",
    imageAlt: "Sourdough cinnamon rolls from Sweet Earth Delights",
    shortDesc: "Soft sourdough roll with brown sugar cinnamon filling and a light glaze.",
    description:
      "A soft cinnamon roll made with naturally fermented sourdough, swirled with brown sugar and cinnamon butter, baked until golden and finished with a light glaze. Best warmed up.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Butter",
      "Milk",
      "Eggs",
      "Sugar",
      "Brown sugar",
      "Cinnamon",
      "Sea salt",
      "Yeast",
      "Vanilla extract",
      "Powdered sugar (glaze)",
    ],
    allergens:
      "Contains wheat, milk, and eggs. Baked in a home kitchen that is not subject to regulation and inspection by the regulatory authority, and may contain allergens.",
  },
  "raw-local-honey": {
    slug: "raw-local-honey",
    name: "Raw Local Honey",
    category: "other",
    categoryLabel: "Other",
    price: "$12.00",
    size: "8 oz jar",
    image: "images/raw-local-honey-omaha.jpg",
    imageAlt: "Raw local honey from Sweet Earth Delights",
    shortDesc: "Nebraska honey from a local apiary. Pairs well with our sourdough.",
    description:
      "Raw local honey from a Nebraska apiary, sold in partnership with Sweet Earth Delights. Unfiltered and perfect drizzled over toast, stirred into tea, or paired with our sourdough on a cheese board. Availability may vary by season.",
    ingredients: ["Raw Nebraska honey"],
    allergens:
      "Not baked in our kitchen. Packaged for resale from a local apiary.",
  },
  "free-range-eggs": {
    slug: "free-range-eggs",
    name: "Free Range Eggs",
    category: "other",
    categoryLabel: "Other",
    price: "$8.00",
    size: "Per dozen",
    image: "images/free-range-eggs.jpg",
    imageAlt: "Free range eggs from Sweet Earth Delights",
    shortDesc: "Fresh free range eggs from a local farm, available when in stock.",
    description:
      "A dozen free range eggs sourced from a local farm and offered alongside our bakes when available. Reach out ahead to confirm stock for your pickup or market order.",
    ingredients: ["Free range eggs"],
    allergens:
      "Contains eggs. Sourced from a local farm and handled separately from our baked goods.",
  },
};
