window.SWEET_EARTH_PRODUCTS = {
  "classic-sourdough-loaf": {
    slug: "classic-sourdough-loaf",
    name: "Classic Sourdough Loaf",
    category: "bread",
    categoryLabel: "Bread",
    price: "$9.00",
    size: "~1 lb loaf",
    image: "images/sourdough-made-daily-in-omaha.jpg",
    imageAlt: "Classic sourdough loaf from Sweet Earth Delights",
    shortDesc: "Long-fermented loaf with a golden crust and tangy, open crumb.",
    description:
      "Our signature loaf starts with a mature sourdough starter and a long, cool ferment. The dough is shaped by hand and baked until the crust is deep golden and crackly, with an open, tangy crumb inside. Slice it for sandwiches, toast it for breakfast, or tear off a piece with butter at the table.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Sea salt",
    ],
    allergens: "Contains wheat. Baked in a home kitchen that also handles eggs, dairy, and tree nuts.",
  },
  "country-sourdough": {
    slug: "country-sourdough",
    name: "Country Sourdough",
    category: "bread",
    categoryLabel: "Bread",
    price: "$10.00",
    size: "~1.25 lb round",
    image: "images/true-sourdough-bread-omaha.jpg",
    imageAlt: "Country sourdough round from Sweet Earth Delights",
    shortDesc: "Rustic round with a hearty crust. Our everyday table bread.",
    description:
      "A round country loaf with a thicker crust and a sturdy crumb that holds up to soup, sandwiches, and next-day toast. We keep the ingredient list short and let fermentation do the work. This is the loaf a lot of our regulars pick up every week.",
    ingredients: [
      "Unbleached wheat flour",
      "Whole wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Sea salt",
    ],
    allergens: "Contains wheat. Baked in a home kitchen that also handles eggs, dairy, and tree nuts.",
  },
  "seeded-sourdough": {
    slug: "seeded-sourdough",
    name: "Seeded Sourdough",
    category: "bread",
    categoryLabel: "Bread",
    price: "$10.00",
    size: "~1 lb loaf",
    image: "images/sourdough-bread-in-bellevue-ne-fresh.jpg",
    imageAlt: "Seeded sourdough loaf from Sweet Earth Delights",
    shortDesc: "Country dough finished with sunflower, flax, and sesame seeds.",
    description:
      "The same slow-fermented country dough we are known for, rolled in a mix of sunflower, flax, and sesame seeds before baking. The seeds toast in the oven and add crunch and nutty flavor to every slice.",
    ingredients: [
      "Unbleached wheat flour",
      "Whole wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Sunflower seeds",
      "Flax seeds",
      "Sesame seeds",
      "Sea salt",
    ],
    allergens: "Contains wheat and sesame. Baked in a home kitchen that also handles eggs, dairy, and tree nuts.",
  },
  "same-day-boule": {
    slug: "same-day-boule",
    name: "Same-Day Boule",
    category: "bread",
    categoryLabel: "Bread",
    price: "$9.00",
    size: "~1 lb boule",
    image: "images/sourdough-bread-2-omaha.jpg",
    imageAlt: "Same-day sourdough boule from Sweet Earth Delights",
    shortDesc: "Mixed and baked to order when our schedule allows. Ask ahead.",
    description:
      "When our bake schedule has room, we can mix and bake a boule the same day you need it. Availability depends on the week, so reach out ahead of time. Same honest dough and hand shaping as our standard loaves.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Sea salt",
    ],
    allergens: "Contains wheat. Baked in a home kitchen that also handles eggs, dairy, and tree nuts.",
  },
  "plain-bagels": {
    slug: "plain-bagels",
    name: "Plain Bagels (6)",
    category: "bagels",
    categoryLabel: "Bagels",
    price: "$10.00",
    size: "6 pack",
    image: "images/sweet-earth-bagels.jpg",
    imageAlt: "Plain bagels from Sweet Earth Delights",
    shortDesc: "Hand-rolled, boiled, and baked the same morning you pick up.",
    description:
      "Six plain bagels rolled by hand, boiled, and baked the morning of your pickup. Chewy inside with a glossy crust. Toast them, schmear them, or use them for sandwiches.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Barley malt syrup",
      "Sea salt",
      "Yeast",
    ],
    allergens: "Contains wheat. Baked in a home kitchen that also handles eggs, dairy, sesame, and tree nuts.",
  },
  "everything-bagels": {
    slug: "everything-bagels",
    name: "Everything Bagels (6)",
    category: "bagels",
    categoryLabel: "Bagels",
    price: "$12.00",
    size: "6 pack",
    image: "images/bagels-sweet-earth-2.jpg",
    imageAlt: "Everything bagels from Sweet Earth Delights",
    shortDesc: "Six bagels topped with everything seasoning, baked fresh.",
    description:
      "Six bagels finished with everything seasoning before baking. Same hand-rolled and boiled process as our plain bagels, with garlic, onion, sesame, and poppy seeds on top.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Barley malt syrup",
      "Sea salt",
      "Yeast",
      "Everything seasoning (sesame seeds, poppy seeds, dried garlic, dried onion, salt)",
    ],
    allergens: "Contains wheat and sesame. Baked in a home kitchen that also handles eggs, dairy, and tree nuts.",
  },
  "cinnamon-roll": {
    slug: "cinnamon-roll",
    name: "Cinnamon Roll",
    category: "pastries",
    categoryLabel: "Pastries",
    price: "$4.50",
    size: "Single roll",
    image: "images/cinnamon-rolls-omaha-sweet-earth.jpg",
    imageAlt: "Cinnamon roll from Sweet Earth Delights",
    shortDesc: "Soft roll with brown sugar cinnamon filling and a light glaze.",
    description:
      "A single soft cinnamon roll with brown sugar and cinnamon butter swirled through the dough, baked until golden and finished with a light glaze. Best warmed up. We bake these in small batches alongside our bread schedule.",
    ingredients: [
      "Unbleached wheat flour",
      "Butter",
      "Milk",
      "Eggs",
      "Sugar",
      "Brown sugar",
      "Cinnamon",
      "Sea salt",
      "Yeast",
      "Vanilla extract",
      "Powdered sugar (glaze)",
    ],
    allergens: "Contains wheat, milk, eggs, and butter. Baked in a home kitchen that also handles tree nuts.",
  },
  "seasonal-pastry-box": {
    slug: "seasonal-pastry-box",
    name: "Seasonal Pastry Box",
    category: "pastries",
    categoryLabel: "Pastries",
    price: "$18.00",
    size: "4 to 6 pieces",
    image: "images/sweet-earth-delights-2-hero.jpg",
    imageAlt: "Seasonal pastry box from Sweet Earth Delights",
    shortDesc: "A mixed box of whatever we are baking that week. Contents vary.",
    description:
      "A curated box of pastries from whatever we are working on that week. Might include croissants, morning buns, fruit danishes, or seasonal specialties. Contents change with the bake schedule. Tell us if you are ordering for a specific day and we will let you know what is available.",
    ingredients: [
      "Varies by selection",
      "Typically includes unbleached wheat flour, butter, milk, eggs, sugar, and seasonal fruit or fillings",
    ],
    allergens: "Contains wheat, milk, eggs, and butter. Specific allergens vary by box. Baked in a home kitchen that also handles tree nuts.",
  },
  "butter-croissant": {
    slug: "butter-croissant",
    name: "Butter Croissant",
    category: "pastries",
    categoryLabel: "Pastries",
    price: "$4.00",
    size: "Single pastry",
    image: "images/sweet-earth-bread-23.jpg",
    imageAlt: "Butter croissant from Sweet Earth Delights",
    shortDesc: "Laminated with butter and baked until flaky at the edges.",
    description:
      "A classic butter croissant laminated by hand and baked until the outside is flaky and golden. Light and buttery inside with visible layers. Available on pastry bake days while supplies last.",
    ingredients: [
      "Unbleached wheat flour",
      "Butter",
      "Milk",
      "Sugar",
      "Sea salt",
      "Yeast",
    ],
    allergens: "Contains wheat, milk, and butter. Baked in a home kitchen that also handles eggs and tree nuts.",
  },
  "chocolate-chip-cookies": {
    slug: "chocolate-chip-cookies",
    name: "Chocolate Chip Cookies (6)",
    category: "treats",
    categoryLabel: "Treats",
    price: "$9.00",
    size: "6 pack",
    image: "images/sweet-earth-delights-4.jpg",
    imageAlt: "Chocolate chip cookies from Sweet Earth Delights",
    shortDesc: "Six cookies with dark chocolate chips, baked soft in the center.",
    description:
      "Six chocolate chip cookies made with brown butter, dark chocolate chips, and a sprinkle of sea salt. Baked so the edges set and the centers stay soft. A regular add-on for pickup orders.",
    ingredients: [
      "Unbleached wheat flour",
      "Butter",
      "Brown sugar",
      "Sugar",
      "Eggs",
      "Vanilla extract",
      "Dark chocolate chips",
      "Sea salt",
      "Baking soda",
    ],
    allergens: "Contains wheat, milk, eggs, and butter. Baked in a home kitchen that also handles tree nuts.",
  },
  "english-muffins": {
    slug: "english-muffins",
    name: "English Muffins (4)",
    category: "treats",
    categoryLabel: "Treats",
    price: "$8.00",
    size: "4 pack",
    image: "images/english-muffins.jpg",
    imageAlt: "English muffins from Sweet Earth Delights",
    shortDesc: "Sourdough muffins with a nooks-and-crannies crumb. Split and toast.",
    description:
      "Four sourdough English muffins cooked on the griddle for that classic nooks-and-crannies texture. Split with a fork, toast until crisp, and finish with butter and jam or use for breakfast sandwiches.",
    ingredients: [
      "Unbleached wheat flour",
      "Water",
      "Sourdough starter (wheat flour, water)",
      "Cornmeal",
      "Sea salt",
      "Baking soda",
    ],
    allergens: "Contains wheat. Baked in a home kitchen that also handles eggs, dairy, and tree nuts.",
  },
  "raw-local-honey": {
    slug: "raw-local-honey",
    name: "Raw Local Honey",
    category: "treats",
    categoryLabel: "Treats",
    price: "$12.00",
    size: "8 oz jar",
    image: "images/raw-local-honey-omaha.jpg",
    imageAlt: "Raw local honey from Sweet Earth Delights",
    shortDesc: "Nebraska honey from a local apiary. Pairs well with our sourdough.",
    description:
      "Raw local honey from a Nebraska apiary, sold in partnership with Sweet Earth Delights. Unfiltered and perfect drizzled over toast, stirred into tea, or paired with our sourdough on a cheese board. Availability may vary by season.",
    ingredients: ["Raw Nebraska honey"],
    allergens: "Not baked in our kitchen. Packaged for resale from a local apiary.",
  },
};
